INSERT INTO `evaluacions` (`id`, `nombre`, `tipo`, `valor`, `descripcion`, `puntaje`, `observacion`, `status`, `created_at`, `updated_at`) VALUES
(1, 'C-1', 'CRITERIO', NULL, 'Debe beneficiar a la mayor cantidad de familias/juntas vecinales involucradas.', '1.00', NULL, 'ACTIVO', NULL, NULL),
(2, 'C-2', 'CRITERIO', NULL, 'Proyecto que atienda a infraestructuras públicas de salud, educación y/o que se complementen con otras intervenciones realizadas con anterioridad', '1.00', NULL, 'ACTIVO', NULL, NULL),
(3, 'C-3', 'CRITERIO', NULL, 'El proyecto no debe encontrarse en áreas y/o zonas de riesgos naturales y geológicos que puedan comprometer a la infraestructura.', '1.00', NULL, 'ACTIVO', NULL, NULL),
(4, 'R-1', 'REQUISITO', NULL, 'Solicitud de financiamiento del proyecto por las Juntas Vecinales y/o GAMs y/o GAIOCs u otras organizaciones sociales debidamente constituidas y reconocidas en el ordenamiento vigente (Personería Jurídica para J.V. y/o OTBs)', '1.00', NULL, 'ACTIVO', NULL, NULL),
(5, 'R-2', 'REQUISITO', NULL, 'Monto máximo por proyecto a ser financiado no podrá ser mayor a Bs 3.000.000.- (Tres Millones 00/100 bolivianos.) (De acuerdo a la convocatoria MPD)', '1.00', NULL, 'ACTIVO', NULL, NULL),
(6, 'R-3', 'REQUISITO', NULL, 'Certificación escrita de existencia de servicios (agua potable, alcantarillado sanitario, etc) por las empresas proveedoras o administradoras de estos servicios. A excepción de los Municipios con categoría “A” (según ROP numeral 2.5. punto vii).', '1.00', NULL, 'ACTIVO', NULL, NULL),
(7, 'R-4', 'REQUISITO', NULL, 'Acta de Consenso Social de las Organizaciones Sociales o Juntas Vecinales, para la ejecución del proyecto (De acuerdo a Usos y Costumbres).', '1.00', NULL, 'ACTIVO', NULL, NULL),
(8, 'R-5', 'REQUISITO', NULL, 'Acta de compromiso para la ejecución de cordones de acera por los beneficiarios y/o municipio.\r\nLos cordones de acera deberán estar concluidos previamente al inicio del proceso de contratación del proyecto. (según ROP numeral 2.5. punto v).\r\n', '1.00', NULL, 'ACTIVO', NULL, NULL),
(9, 'R-6', 'REQUISITO', NULL, 'Planimetría Aprobada por el GAM correspondiente de los lugares de intervención que permita la ejecución del proyecto donde se muestre ancho de vía y si corresponde ubicación de áreas verdes. A excepción de los municipios de categoría A. (según ROP numeral 2.5. punto iv).', '1.00', NULL, 'ACTIVO', NULL, NULL),
(10, 'R-7', 'REQUISITO', NULL, 'Acta de Compromiso para firmar el Convenio CTF /CFP por las Juntas Vecinales y/o GAMs y/o GAIOCs u otras organizaciones sociales.', '1.00', NULL, 'ACTIVO', NULL, NULL),
(11, 'I-1', 'INGENIERIA', NULL, 'Resumen Ejecutivo (Antecedentes, Justificación, Objetivos, Costo de Inversión, Ubicación Geográfica y tiempo de ejecución)', '1.00', '', 'ACTIVO', NULL, NULL),
(12, 'I-2', 'INGENIERIA', NULL, 'Diagnóstico del proyecto /Estudio Socioeconómico\r\n(Considerando el alcance del proyecto, el mismo deberá contener un diagnóstico de situación actual, área de influencia del proyecto; características físicas, condiciones socioeconómicas de los beneficiarios).\r\n', '1.00', NULL, 'ACTIVO', NULL, NULL),
(13, 'I-3', 'INGENIERIA', NULL, 'Localización (Croquis de Ubicación)', '1.00', NULL, 'ACTIVO', NULL, NULL),
(14, 'I-4', 'INGENIERIA', NULL, 'Presupuesto General ', '1.00', NULL, 'ACTIVO', NULL, NULL),
(15, 'I-5', 'INGENIERIA', '', 'Precios Unitarios (Verificación de precios de los materiales acorde al lugar de intervención)', '1.00', NULL, 'ACTIVO', NULL, NULL),
(16, 'I-6', 'INGENIERIA', NULL, 'Cómputos Métricos', '1.00', NULL, 'ACTIVO', NULL, NULL),
(17, 'I-7', 'INGENIERIA', NULL, 'Cronograma de Ejecución.', '1.00', NULL, 'ACTIVO', NULL, NULL),
(18, 'I-8', 'INGENIERIA', NULL, 'Planos Constructivos (planos de planta, detalles constructivos de las obras de arte, perfil longitudinal y transversal )', '1.00', NULL, 'ACTIVO', NULL, NULL),
(19, 'I-9', 'INGENIERIA', NULL, 'Especificaciones Técnicas.', '1.00', NULL, 'ACTIVO', NULL, NULL),
(20, 'I-10', 'INGENIERIA', NULL, 'Informe Fotográfico (Que muestre las actividades a ser implementadas)', '1.00', NULL, 'ACTIVO', NULL, NULL);
